#!/bin/bash
shopt -s extglob

version=$1 bin_name=${2:-bash$version}

mkdir -p build/bin &&
if [[ $version = devel ]]; then
    mkdir -p build/loadables &&
    cd bash &&
    ./configure &&
    make &&
    cp bash "../build/bin/$bin_name" &&
    # loadable builtins
    cd examples/loadables &&
    make &&
    for file in !(*.*); do
        [[ -f $file && -x $file ]] || continue
        cp "${file}" ../../../build/loadables
    done
    
    exit
fi

cd build &&
wget -c -O "bash-$version.tar.gz" "http://ftp.gnu.org/gnu/bash/bash-$version.tar.gz" &&
gzip -cd "bash-$version.tar.gz" | pax -r || exit

configure_opts=()
patches=
case $version in
    1.14.7)
        # Patch it up so it'll build on 64-bit
        patch -p0 << 'EOF'
diff -ur bash-1.14.7.orig/machines.h bash-1.14.7/machines.h
--- bash-1.14.7.orig/machines.h	1995-12-18 20:13:22.000000000 +0100
+++ bash-1.14.7/machines.h	2012-09-16 20:04:56.545130869 +0200
@@ -76,6 +76,32 @@
 #define MACHINE_CFLAGS
 
 /* **************************************************************** */
+/*                                                                  */
+/*                      x86 64-bit machines                         */
+/*                                                                  */
+/* **************************************************************** */
+
+#if defined (__x86_64__) && defined (__linux__)
+#  define M_MACHINE "x86_64"
+#  define M_OS "Linux"
+#  define SYSDEP_CFLAGS -DHAVE_GETDTABLESIZE -DHAVE_BCOPY \
+      	  -DHAVE_GETPW_DECLS -DHAVE_GETHOSTNAME
+#  define REQUIRED_LIBRARIES
+#  define HAVE_GETGROUPS
+#  define HAVE_STRERROR
+#  define VOID_SIGHANDLER
+#  define HAVE_SYS_SIGLIST
+#  define SEARCH_LIB_NEEDS_SPACE
+#  if defined (__GNUC__)
+#    define HAVE_FIXED_INCLUDES
+#  endif /* __GNUC__ */
+#  undef USE_GNU_MALLOC
+#  undef HAVE_SETLINEBUF
+#  undef HAVE_GETWD
+#endif  /* __x86_64__ && __linux__ */
+
+
+/* **************************************************************** */
 /*								    */
 /*			Sun Microsystems Machines	      	    */
 /*								    */
@@ -889,8 +915,6 @@
 #    define HAVE_STRERROR
 #    define VOID_SIGHANDLER
 #    define HAVE_SYS_SIGLIST
-#    define HAVE_VFPRINTF
-#    define HAVE_VARARGS_H
 #    define SEARCH_LIB_NEEDS_SPACE
 #    if defined (__GNUC__)
 #      define HAVE_FIXED_INCLUDES
diff -ur bash-1.14.7.orig/support/getcppsyms.c bash-1.14.7/support/getcppsyms.c
--- bash-1.14.7.orig/support/getcppsyms.c	1995-05-31 17:02:14.000000000 +0200
+++ bash-1.14.7/support/getcppsyms.c	2012-09-16 19:57:00.501120007 +0200
@@ -422,6 +422,12 @@
 #if defined (vax)
   printf (" -Dvax");
 #endif /* vax */
+#if defined (__x86_64)
+  printf (" -D__x86_64");
+#endif /* __x86_64 */
+#if defined (__x86_64__)
+  printf (" -D__x86_64__");
+#endif /* __x86_64__ */
 
   printf ("\n");
   exit (0);
EOF
    ;;
    2.05b)
        # bash-2.05b's malloc doesn't build with newer gcc
        configure_opts=( --without-bash-malloc )
        patches=1
    ;;
    3.[0-2]|4.[0-2])
        patches=1
    ;;
esac

if ((patches)); then
    wget -r --level=1 -A 'bash*-[0-9][0-9][0-9]' -nH --cut-dirs=2 "http://ftp.gnu.org/gnu/bash/bash-$version-patches/" || exit
fi

cd "bash-$version" || exit

if ((patches)); then
    cat "../bash-$version-patches"/bash*-[0-9][0-9][0-9] | patch -p0 || exit
fi

./configure "${configure_opts[@]}" &&
make &&
cp bash "../bin/$bin_name"
