#!/bin/bash

mkdir -p build/bin &&
cd build &&
wget -c -O ex-vi.tar.bz2 "http://sourceforge.net/projects/ex-vi/files/latest/download" &&
bzip2 -cd ex-vi.tar.bz2 | pax -rs ',[^/]*,ex-vi,' &&
cd ex-vi &&
make &&
cp ex ../bin
