#!/bin/bash -x
shopt -s extglob

shell=$1 version=$2 bin_name=${3:-$shell$version}

mkdir -p build/{bin,man/man1} || exit

case $shell in
    mksh)
        cd build &&
        wget -c -O "mksh-$version.tgz" "https://www.mirbsd.org/MirOS/dist/mir/mksh/snapshot/mksh-$version.tgz" &&

        gzip -cd "mksh-$version.tgz" | pax -r &&
        cd mksh &&
        sh Build.sh &&
        cp mksh "../bin/$bin_name" &&
        cp mksh.1 "../man/man1/$bin_name.1"
    ;;
    bourne)
        cd build &&
        wget -c -O heirloom-sh.tar.bz2 "http://sourceforge.net/projects/heirloom/files/heirloom-sh/$version/heirloom-sh-$version.tar.bz2/download" &&
        bzip2 -cd heirloom-sh.tar.bz2 | pax -rs '|^[^/]*|heirloom-sh|' &&
        cd heirloom-sh &&
        make &&
        cp sh ../bin/$bin_name &&
        cp sh.1 ../man/man1/$bin_name.1
    ;;
    bash) : ;; #handled below
    *) exit 1;;
esac

# bash
case $version in
    devel)
        mkdir -p build/loadables &&
        cd bash &&
        ./configure &&
        make &&
        cp bash "../build/bin/$bin_name" &&
        cp doc/bash.1 "../build/man/man1/$bin_name.1" &&
        # loadable builtins
        cd examples/loadables &&
        make &&
        for file in !(*.*); do
            [[ -f $file && -x $file ]] || continue
            cp "${file}" ../../../build/loadables
        done
    ;;
    1.14.7)
        cd "build/bash-$version" &&
        make &&
        cp bash "../bin/$bin_name" &&
        cp documentation/bash.1 "../man/man1/$bin_name.1"
    ;;
    *)
        cd "build/bash-$version" &&
        ./configure &&
        make &&
        cp bash "../bin/$bin_name" &&
        cp doc/bash.1 "../man/man1/$bin_name.1"
    ;;
esac
