#!/bin/bash

version=$1 bin_name=${2:-mksh$version}

mkdir -p build/bin &&
cd build &&
wget -c -O "mksh-$version.tgz" "https://www.mirbsd.org/MirOS/dist/mir/mksh/snapshot/mksh-$version.tgz" &&

gzip -cd "mksh-$version.tgz" | pax -r &&
cd mksh &&
sh Build.sh &&
cp mksh "../bin/$bin_name"
