#!/bin/bash -x

t=${1:-4}
declare -A triggers='()'
while read -r trigger shell; do
    triggers[$trigger]=$shell
done < ./triggers
[[ ${triggers[$t]} ]] || exit

output=$(./limitcmd.pl "${triggers[$t]}" "$2" | head -c 4242 | tr -d '\r' | awk '{ do { print substr($0, 1, 120); $0 = substr($0, 121); } while(length($0)>0);  }'; exit ${PIPESTATUS[0]}; )
result=$?
lines=$(wc -l <<< "$output")

shopt -s extglob

if [[ $output == *( ) ]] 
then
	if (( result > 0 )) 
	then
		echo "no output within the time limit"
	else
		echo "no output"
	fi
    exit 0
fi

if (( lines <= 3 )); then 
    printf '%s\n' "$output"; 
    exit 0
fi

read -r url < <(./paste <<< "$output")
if [[ -n $url ]] 
then
    etc="etc... ( $url )"
else
    etc="and so forth... (but now the pastebin is sick of me)"
fi

printf '%s\n' "$output" | head -n 2
printf '%s\n' "$etc"


