#!/bin/bash
image="$1"
state=$2

mkfifo fifo # &> /dev/null
[[ -r fifo && -w fifo && -p fifo ]] || { echo "fifo fail"; exit 1; } 

< fifo kvm -kernel bzImage -append "-- $state" -initrd initramfs.cpio.gz  -hda "$image" -net none -m 64 -nographic -no-kvm |
    while read -r f
    do
        printf '%s\n' "$f" >&2
        if [[ $f = $'Ready\r' ]]; then
            printf '\x01c\nsavevm %s\nquit\n' "$state"
        fi
    done > fifo

rm -f fifo
