#! /usr/bin/env python

from shbot import Shbot

def main():
    import sys
    if len(sys.argv) != 5:
        print("Usage: shbot <server[:port]> <channel> <nickname> <password>")
        sys.exit(1)

    s = sys.argv[1].split(":", 1)
    server = s[0]
    if len(s) == 2:
        try:
            port = int(s[1])
        except ValueError:
            print("Error: Erroneous port.")
            sys.exit(1)
    else:
        port = 6667
    channels = [sys.argv[2]]
    nickname = sys.argv[3]
    password = sys.argv[4]

    bot = Shbot(channels, nickname, server, port, password)
    bot.start()

if __name__ == "__main__":
    main()
