#!/bin/bash
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/full c 1 7
ln -s console /dev/tty
hostname bunnies
mount -t proc none /proc 

stty -echo
export PS1='$(mkdir /tmp/... 2>/dev/null||command echo o >/proc/sysrq-trigger)'
export PS2="Missing terminating quote, bracket or keyword"
export HOME=/root
cd "$HOME"

rm /README

shell=/bin/bash

case $2 in
    _[2-4]) shell=/bin/bash${2#_} ;;
    _k93) shell=/bin/ksh ;;
    _sh) shell=/bin/sh ;;
esac

"$shell" -l
echo "(shell exited with $?)"
echo o > /proc/sysrq-trigger
sleep 10
