#!/bin/bash
mknod -m 660 /dev/ttyS0 c 4 64
mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/full c 1 7
mknod -m 644 /dev/random c 1 8
mknod -m 644 /dev/urandom c 1 9
ln -s ttyS0 /dev/tty
hostname bunnies
mkdir -p /proc /tmp
chmod 1777 /tmp
mount -t proc none /proc 

stty -echo
export PS1='$({ mkdir /tmp/... || echo o >/proc/sysrq-trigger; set +x; } 2>/dev/null)'
export PS2="Missing terminating quote, bracket or keyword"
export HOME=/root
cd "$HOME"

rm /README

shell=/bin/bash

case $2 in
    _[23]) shell=/bin/bash${2#_} ;;
    _k93) shell=/bin/ksh ;;
    _sh) shell=/bin/sh ;;
esac

setsid "$shell" -l
echo "(shell exited with $?)"
echo o > /proc/sysrq-trigger
sleep 10
