#!/usr/bin/env bash

touch triggers || exit
while (( $# >= 3 )); do
    awk -v t="$1" -v e="$2" -v v="$3" '
        BEGIN { FS = "\t+"; OFS = "\t" }
        $1 == t { $2 = e; $3 = v; replaced = 1 }
        { print }
        END { if (!replaced) print t, e, v }' triggers > triggers.new &&
    mv triggers.new triggers || exit
    shift 3
done
