#!/usr/bin/env bash
shopt -s extglob

shell=$1 version=$2 bin_name=${3:-$shell$version}
srcdir=$PWD

if [[ -v VERBOSE ]]; then
    mkdir() { command mkdir -v "$@"; }
    cp() { command cp -v "$@"; }
    rm() { command rm -v "$@"; }
    bzip2() { command bzip2 -v "$@"; }
fi

mkdir -p build/{bin,man/man1} || exit

case $shell in
    bourne)
        cd build &&
        wget -c -O "$srcdir/sources/heirloom-sh.tar.bz2" \
            "http://sourceforge.net/projects/heirloom/files/heirloom-sh/$version/heirloom-sh-$version.tar.bz2/download" &&
        bzip2 -cd "$srcdir/sources/heirloom-sh.tar.bz2" | 
            pax -rs '|^[^/]*|heirloom-sh|' &&
        cd heirloom-sh &&
        make &&
        cp sh "../bin/$bin_name" &&
        cp sh.1 "../man/man1/$bin_name.1"
        exit
    ;;
    dash)
        cd build/dash-$version &&
        ./autogen.sh &&
        ./configure &&
        make &&
        cp src/dash "../bin/$bin_name" &&
        cp src/dash.1 "../man/man1/$bin_name.1"
        exit
    ;;
	posh)
		cd "build/posh-$version" &&
		aclocal &&
		autoreconf -i &&
		./configure &&
		make &&
		cp posh "../bin/$bin_name" &&
		cp posh.1 "../man/man1/$bin_name.1"
		exit
	;;
    bash) : ;; #handled below
    *) exit 1;;
esac

# bash
case $version in
    devel)
        mkdir -p build/loadables &&
        cd build/bash-devel &&
        ./configure &&
        make &&
        cp bash "../bin/$bin_name" &&
        cp doc/bash.1 "../man/man1/$bin_name.1" &&
        # loadable builtins
        cd examples/loadables &&
        make &&
        for file in !(*.*); do
            [[ -f $file && -x $file ]] || continue
            #strip "$file"
            cp "${file}" ../../../loadables
        done
    ;;
    1.14.7)
        cd "build/bash-$version" &&
        make &&
        cp bash "../bin/$bin_name" &&
        cp documentation/bash.1 "../man/man1/$bin_name.1"
    ;;
    *)
        cd "build/bash-$version" &&
        rm -f y.tab.[co] &&
        ./configure &&
        make &&
        cp bash "../bin/$bin_name" &&
        cp doc/bash.1 "../man/man1/$bin_name.1"
    ;;
esac
