#!/bin/bash

srcdir=$PWD
wget -c -O "sources/adu.tar.Z" "http://twkm.freeshell.org/adu.tar.Z" &&
mkdir -p build/{bin,adu} &&
cd build/adu &&
gzip -cd "$srcdir/sources/adu.tar.Z" | pax -r &&
make -f adu.mak &&
cp adu ../bin &&
