#!/usr/bin/env bash

if [[ $VERBOSE = 1 ]]; then
    cp() { command cp -v "$@"; }
    mkdir() { command mkdir -v "$@"; }
    rm() { command rm -v "$@"; }
fi

case $(uname -m) in
    x86_64) bit=64 ;;
    *) bit=32 ;;
esac
kernelver=$(make -sC sources/linux kernelversion) || exit

printf 'Building %d-bit linux %s.\n' "$bit" "$kernelver"

rm -rf build/kernel && mkdir -p build/kernel || exit
if (( bit == 64 )); then
    cp kernel64.config build/kernel/.config
else
    cp kernel.config build/kernel/.config
fi || exit
make -C sources/linux silentoldconfig O="$PWD/build/kernel" &&
make -C build/kernel &&
cp build/kernel/arch/x86/boot/bzImage build/bzImage
