#!/usr/bin/env bash

srcdir=$PWD

mkdir -p sources/ build/{bin,man/man1} &&
cd build &&
wget -c -O "$srcdir/sources/ex-vi.tar.bz2" \
    "http://sourceforge.net/projects/ex-vi/files/latest/download" &&
bzip2 -cd "$srcdir/sources/ex-vi.tar.bz2" | pax -rs ',[^/]*,ex-vi,' &&
cd ex-vi &&
make &&
cp ex ../bin &&
cp ex.1 ../man/man1/ex.1
