#!/bin/bash

url=$1 kernel=${url##*/} dir=${kernel%.tar.*}
srcdir=$PWD

mkdir -p sources/ build/ &&
cd build || exit

wget -c -O "$srcdir/sources/$kernel" "$url" &&
case $kernel in
    *.tar.xz)  xz -cd    "$srcdir/sources/$kernel" ;;
    *.tar.bz2) bzip2 -cd "$srcdir/sources/$kernel" ;;
    *.tar.gz)  gzip -cd  "$srcdir/sources/$kernel" ;;
    *) exit 1 ;;
esac | pax -r &&
case $(uname -m) in
    x86_64) cp ../kernel64.config "$dir/.config" ;;
    *) cp ../kernel.config "$dir/.config" ;;
esac &&
cd "$dir" &&
make silentoldconfig &&
make &&
cp arch/x86/boot/bzImage ../bzImage
