#!/bin/bash

if [[ $1 != *.bz2 ]]; then
    printf 'No url or filename to a linux bzip2ed tarball provided.\n' >&2
    exit 1
fi
mkdir -p build/ &&
cd build || exit

kernel=$1
if [[ ! -f $kernel ]]; then # assuming url
    wget -nc "$kernel" || exit
    kernel=${kernel##*/}
fi

bzip2 -cd "$kernel" | pax -r &&
dir=${kernel##*/} dir=${dir%.tar.bz2} &&
case $(uname -m) in
    x86_64) cp ../kernel64.config "$dir/.config" ;;
    *) cp ../kernel.config "$dir/.config" ;;
esac || exit
cd "$dir" &&
make silentoldconfig &&
make &&
cp arch/x86/boot/bzImage ../bzImage
