#!/bin/bash
# usage: extract-from-git build/bash-x.y.z

die() { local ret=$?; printf '%s\n' "$@" >&2; exit "$ret"; }

declare -A versions='(
    [bash-1.14.7]=726f63884db0132f01745f1fb4465e6621088ccf
    [bash-2.05b]=7117c2d221b2aed4ede8600f6a36b7c1454b4f55
    [bash-3.2.48]=f1be666c7d78939ad775078d290bec2758fa29a2
    [bash-4.2.45]=f281b8f4f8936b2713966274d9f8508a9f0910e4
    [bash-devel]=origin/devel
)'

base=${1##*/}

[[ ${versions[$base]} ]] || die "Unkown version: $base"

mkdir -p "$1" || exit 
{
    cd bash && 
    git archive --prefix="$1/" --format=tar "${versions[$base]}"
} | pax -r

if [[ -f patches/$base ]]; then
    { cd "$1" && patch -p1; } < "patches/$base"
fi
